name: My Portfolio and Blog
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  


robots: all

permalink: /:categories/:title/

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "John Prasad"
  - scope:
      path: "_portfolio"
      type: "portfolio"
    values:
      layout: "custom"

include:
  - pages

navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Projects
    url: /projects/
  - title: Education
    url: /education/
