name: My Cyber Security Blog
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title/

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
      author: "John Prsad"
  - scope:
      path: "portfolio"
      type: "portfolio"
    values:
      layout: "portfolio"

include:
  - pages
